# Generated by Django 2.1.3 on 2019-05-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grass_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Growthtpye', models.CharField(blank=True, max_length=200)),
                ('Cultivar', models.CharField(blank=True, max_length=200)),
                ('Commonname', models.CharField(blank=True, max_length=200)),
                ('Scientificname', models.CharField(blank=True, max_length=200)),
                ('Wiki', models.CharField(blank=True, max_length=200)),
                ('Genbank', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'grass',
            },
        ),
    ]
