# Generated by Django 2.1.3 on 2019-05-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grass_db',
            name='Commonname',
        ),
        migrations.RemoveField(
            model_name='grass_db',
            name='Growthtpye',
        ),
        migrations.RemoveField(
            model_name='grass_db',
            name='Scientificname',
        ),
        migrations.AddField(
            model_name='grass_db',
            name='Common_N',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grass_db',
            name='Growth_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grass_db',
            name='Scientific_N',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='grass_db',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
